name: expense_tracker
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  get_it: ^8.0.3
  sqflite: ^2.4.2
  path: ^1.9.1
  mockito: ^5.4.4
  mocktail: ^1.0.4
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  json_annotation: ^4.8.1
  bloc: ^9.0.0
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.1.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  bloc_test: ^10.0.0
flutter:
  uses-material-design: true


  assets:
    - assets/svgs/