// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ2SXmfipcqs7Dd6juyH-nnCIIo2dMq80',
    appId: '1:238220934024:web:37bd462b0f26a40399983d',
    messagingSenderId: '238220934024',
    projectId: 'expense-tracker-525a4',
    authDomain: 'expense-tracker-525a4.firebaseapp.com',
    storageBucket: 'expense-tracker-525a4.firebasestorage.app',
    measurementId: 'G-H8QXMFG0J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByVpi_LiGuyb_Sfg8sxIbPV1jhcR8BLdg',
    appId: '1:238220934024:android:11ab39e36cb6aed499983d',
    messagingSenderId: '238220934024',
    projectId: 'expense-tracker-525a4',
    storageBucket: 'expense-tracker-525a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIEcqjd-JuT2tLknEqT6YPWPrBVZdJN5M',
    appId: '1:238220934024:ios:01fc354af1bdebdb99983d',
    messagingSenderId: '238220934024',
    projectId: 'expense-tracker-525a4',
    storageBucket: 'expense-tracker-525a4.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIEcqjd-JuT2tLknEqT6YPWPrBVZdJN5M',
    appId: '1:238220934024:ios:01fc354af1bdebdb99983d',
    messagingSenderId: '238220934024',
    projectId: 'expense-tracker-525a4',
    storageBucket: 'expense-tracker-525a4.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ2SXmfipcqs7Dd6juyH-nnCIIo2dMq80',
    appId: '1:238220934024:web:a1826e37bc0d2b1199983d',
    messagingSenderId: '238220934024',
    projectId: 'expense-tracker-525a4',
    authDomain: 'expense-tracker-525a4.firebaseapp.com',
    storageBucket: 'expense-tracker-525a4.firebasestorage.app',
    measurementId: 'G-FRXB326YNJ',
  );
}
